
import os, io
from datetime import datetime, timezone
import discord
from discord import app_commands
from discord.ext import commands
from fzd_db import get_db_connection, get_event_schedule
from hostpost_views import WizardView
from build_hostposts import build_posts
from event_post_text import events, help_text, access_roles
from autopost_commands import PostScheduler

''' Output for Draft Posts '''
async def post_draft_posts_to_discord(
    interaction: discord.Interaction, 
    hour_post: list[str], 
    go_posts: list[str], 
    results_posts: list[str], 
    event_results_post: list[str]
    ):
    # Send hour posts
    await interaction.followup.send(hour_post[0], ephemeral=False)
    if len(go_posts) == len(results_posts):
        # interlace posts
        for index, post in enumerate(go_posts):
            await interaction.followup.send(post, ephemeral=False)
            await interaction.followup.send(results_posts[index], ephemeral=False)
    else:
        raise Exception(
            f"Internal error: lists of prix initiation (length = {len(go_posts)}) and results posts (length = {len(results_posts)})are different lengths."
            )
    await interaction.followup.send(event_results_post[0], ephemeral=False)

async def post_post_textfile(
    interaction: discord.Interaction, 
    event: str, 
    event_start_time: datetime, 
    hour_post: list[str], 
    go_posts: list[str], 
    results_posts: list[str], 
    event_results_post: list[str]
    ):
    # Create the large string object for writing to file.
    post_text = hour_post[0] + "\n\n"
    for index, post in enumerate(go_posts):
        post_text += post + "\n\n"
        post_text += results_posts[index] + "\n\n"
    post_text += event_results_post[0]
    
    ''' Write to text file '''
    filename = event + "_" + event_start_time.strftime("%Y-%m-%d %H:%M:%S") + "_posts.txt"
    # Convert text into a byte stream
    buffer = io.BytesIO(post_text.encode('utf-8'))
    # Send it directly
    await interaction.followup.send(
        f"Posts written to attached file {filename} for your records.", 
        file=discord.File(fp=buffer, filename=filename)
        )


''' Event Builder Command Cog Class '''
class EventBuilder(commands.Cog):
    def __init__(self, bot: commands.Bot, event_list) -> None:
        self.bot: commands.Bot = bot
        self.event_list: list[str] | None = event_list

    ''' Autocomplete methods '''
    async def event_autocomplete(self, interaction: discord.Interaction, current: str) -> list[app_commands.Choice[str]]:
        options = [event for event in self.event_list if current.lower() in event.lower()]

        # Return up to 25 results (25=discord limit)
        return [app_commands.Choice(name=event, value=f"{event}") for event in options[:25]]
    
    async def timetype_autocomplete(self, interaction: discord.Interaction, current: str) -> list[app_commands.Choice[str]]:
        options = ["Simple", "Custom"]
        return [app_commands.Choice(name=option, value=f"{option}") for option in options if current.lower() in option.lower()]
    
    

    @app_commands.command(name="event_setup", description="Select event to prepare hosting posts for.")
    @discord.app_commands.checks.has_any_role(*access_roles)
    async def event_setup(self, interaction: discord.Interaction, event: str, num_prix: int, timetype: str = "Simple"):
        if num_prix < 1 or num_prix > 10:
            await interaction.response.send_message("Please choose between 1 and 10.", ephemeral=True)
            return
        
        try:
            # Note that the events listed will only be future events generated by the database weekly.
            async with get_db_connection() as db:
                available_event_dict = await get_event_schedule(db)
            self.event_list = [s['event'] for s in available_event_dict if 'event' in s]

            print(f"Event name: {event}.")
            if not event in [e['fullname'] for e in events]:
                await interaction.response.send_message(
                   "❌  ERROR! Event {event} not found!",
                  ephemeral=True 
                  )
            else:
                default_start_time = next(
                    (item["utc_start"] for item in available_event_dict if item["event"] == event), None)
                default_start_time = default_start_time.replace(tzinfo=timezone.utc)
                use_simple_time = (timetype == "Simple")

                view = WizardView(num_prix, default_start_time, event, use_simple_time)
                await interaction.response.send_message(view.get_content(), view=view)

                timed_out = await view.wait()
    
                # Check why we stopped waiting
                if timed_out:
                    await interaction.followup.send("Selection timed out. Please try again.", ephemeral=True)
                    return
                
                # Build posts using functions in module build_hostposts.
                event_start_time = view.all_results[0]["time"]
                hour_post, go_posts, results_posts, event_results_post = build_posts(event, view.all_results)
                
                # Distribute Posts
                ## To the interaction channel as separate posts
                await post_draft_posts_to_discord(interaction, hour_post, go_posts, results_posts, event_results_post)
                ## To the interaction channel as a text file
                await post_post_textfile(interaction, event, event_start_time, hour_post, go_posts, results_posts, event_results_post)
                ## To the scheduled autoposter, if user selects it.
                print(f"The user selected autopost?: {view.autopost}.")
                if view.autopost:
                    # Run the scheduler module.
                    #   v1 only posts hour_post and go_posts
                    #   v2 allows user interaction on results posts through slash commands.
                    # We are currently in v1.
                    ps = PostScheduler(self.bot)
                    await ps.post_scheduler(event, hour_post, go_posts, view.all_results)
    
                event_prixinfo = view.all_results
                print(f"Prix info collected for {event}: {event_prixinfo}")

        except Exception as e:
            print(f"Exception in event_posts: {e}")
            await interaction.followup.send(
                   "❌  ERROR! currently undefined error",
                  ephemeral=True 
                  )

    @app_commands.command(name="help", description="Information about the HostPost bot.")
    async def help(self, interaction: discord.Interaction):
        await interaction.response.send_message(help_text, ephemeral=False)
 
    @event_setup.error
    async def role_error(self, interaction: discord.Interaction, error):
        if isinstance(error, app_commands.MissingAnyRole):
            await interaction.response.send_message(
                "This command is Circuit Crew only. Hit up a mod if you want to join Circuit Crew.",
                ephemeral=True
                )
        else: raise error


    async def cog_load(self):
        self.event_setup.autocomplete("event")(self.event_autocomplete)
        self.event_setup.autocomplete("timetype")(self.timetype_autocomplete)


async def setup(bot: commands.Bot):
    GUILD_ID=discord.Object(id=os.getenv('SERVER_ID'))
    # initialize list of events
    async with get_db_connection() as db:
        available_event_dict = await get_event_schedule(db)
    event_list = [s['event'] for s in available_event_dict if 'event' in s]
    await bot.add_cog(EventBuilder(bot, event_list), guild=GUILD_ID)